In [1]:
import torch
from sklearn.datasets import make_classification

In [2]:
# make the dataset
X , y = make_classification(
    n_samples = 10 , n_features = 2 , n_informative = 2 , n_redundant = 0, n_classes = 2, 
    random_state = 42
)

In [3]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [4]:
# convert numpy to tensor 
X = torch.from_numpy(X)
y = torch.from_numpy(y)

In [5]:
from torch.utils.data import Dataset , DataLoader

In [6]:
class CustomDataset(Dataset): 
    def __init__(self , features , labels): 
        self.features = features
        self.labels = labels

    def __len__(self): 
        return self.features.shape[0]

    def __getitem__(self , index): 
        return self.features[index] , self.labels[index]

In [7]:
dataset = CustomDataset(X , y) 

In [8]:
len(dataset)

10

In [9]:
dataset[0]

(tensor([ 1.0683, -0.9701], dtype=torch.float64), tensor(1, dtype=torch.int32))

In [10]:
dataloader = DataLoader(dataset = dataset , batch_size = 2 , shuffle = True)

In [11]:
for batch_features , batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("---" * 10)

tensor([[ 1.0683, -0.9701],
        [-0.5872, -1.9717]], dtype=torch.float64)
tensor([1, 0], dtype=torch.int32)
------------------------------
tensor([[-1.1402, -0.8388],
        [-0.9382, -0.5430]], dtype=torch.float64)
tensor([0, 1], dtype=torch.int32)
------------------------------
tensor([[ 1.7273, -1.1858],
        [-2.8954,  1.9769]], dtype=torch.float64)
tensor([1, 0], dtype=torch.int32)
------------------------------
tensor([[-0.7206, -0.9606],
        [ 1.7774,  1.5116]], dtype=torch.float64)
tensor([0, 1], dtype=torch.int32)
------------------------------
tensor([[-1.9629, -0.9923],
        [ 1.8997,  0.8344]], dtype=torch.float64)
tensor([0, 1], dtype=torch.int32)
------------------------------
