In [1]:
import torch

print("Number of GPU: ", torch.cuda.device_count())
print("GPU Name: ", torch.cuda.get_device_name())


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)

Number of GPU:  1
GPU Name:  NVIDIA GeForce RTX 5060 Ti
Using device: cuda


C:\Users\tipto\anaconda3\envs\ml\Lib\site-packages\torch\cuda\__init__.py:283: UserWarning: 
    Found GPU0 NVIDIA GeForce RTX 5060 Ti which is of cuda capability 12.0.
    Minimum and Maximum cuda capability supported by this version of PyTorch is
    (5.0) - (9.0)
    
  warnings.warn(
C:\Users\tipto\anaconda3\envs\ml\Lib\site-packages\torch\cuda\__init__.py:304: UserWarning: 
    Please install PyTorch with a following CUDA
    configurations:  12.8 13.0 following instructions at
    https://pytorch.org/get-started/locally/
    
  warnings.warn(matched_cuda_warn.format(matched_arches))
C:\Users\tipto\anaconda3\envs\ml\Lib\site-packages\torch\cuda\__init__.py:326: UserWarning: 
NVIDIA GeForce RTX 5060 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5060 Ti GPU with PyTorch, please check the instructio

### Creating Tensors

In [4]:
# using empty
a = torch.empty(2 , 3) # resister 2*3 = 6 memory location and these values where already present in these location
a 

tensor([[9.9385e-32, 1.9254e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [5]:
# check type 
type(a)

torch.Tensor

In [6]:
torch.zeros(2 , 2)

tensor([[0., 0.],
        [0., 0.]])

In [7]:
torch.tensor([
    [1,2,3],[4,5,6]
])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
# identity matrix/tensors 
torch.eye(2,2)

tensor([[1., 0.],
        [0., 1.]])

In [9]:
a.shape

torch.Size([2, 3])

In [10]:
# create a empty tensor with same shape of a 
b = torch.empty_like(a)
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
# data types of a tensor 
a.dtype

torch.float32

In [14]:
# changing data types 
a = a.to(torch.int32)

In [15]:
a.dtype

torch.int32

In [16]:
torch.neg(a)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [17]:
b = torch.tensor([1,2,3])
torch.neg(b)

tensor([-1, -2, -3])

In [18]:
e = torch.randint(size = (2,3) , low = 0 , high = 10)
e

tensor([[0, 5, 7],
        [2, 6, 6]])

In [19]:
torch.sum(e)

tensor(26)

In [20]:
# row wise sum 
torch.sum(e , dim = 1)

tensor([12, 14])

In [21]:
# col wise sum 
torch.sum(e , dim = 0)

tensor([ 2, 11, 13])

In [22]:
c = torch.tensor([
    [1,2,3],[4,5,6],[7,8,9]
])

In [25]:
torch.mean(c , dtype = torch.float)

tensor(5.)

In [26]:
# transpose a tensor 
# swap between row(0) and col(1)
torch.transpose(c , dim0 = 1 , dim1 = 0)

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [27]:
c

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### inplace operations 

In [28]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [29]:
m , n

(tensor([[0.9483, 0.0737, 0.1350],
         [0.5392, 0.3809, 0.6248]]),
 tensor([[0.0430, 0.2979, 0.4844],
         [0.5320, 0.5606, 0.5926]]))

In [30]:
# add m + n and store in m 
m.add_(n)

tensor([[0.9913, 0.3716, 0.6194],
        [1.0712, 0.9415, 1.2174]])

In [31]:
m

tensor([[0.9913, 0.3716, 0.6194],
        [1.0712, 0.9415, 1.2174]])

In [32]:
# if we use a = b, here both are sharing same memory. for copy use clone function 
a = m.clone()

In [33]:
a

tensor([[0.9913, 0.3716, 0.6194],
        [1.0712, 0.9415, 1.2174]])