In [1]:
import warnings
warnings.filterwarnings("ignore")
import torch

print("Number of GPU: ", torch.cuda.device_count())
print("GPU Name: ", torch.cuda.get_device_name())


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)

Number of GPU:  1
GPU Name:  NVIDIA GeForce RTX 5060 Ti
Using device: cuda


In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst  Unnamed: 32
0    842302         M        17.99  ...          0.4601                  0.11890          NaN
1    842517         M        20.57  ...          0.2750                  0.08902          NaN
2  84300903         M        19.69  ...          0.3613                  0.08758          NaN
3  84348301         M        11.42  ...          0.6638                  0.17300          NaN
4  84358402         M        20.29  ...          0.2364                  0.07678          NaN

[5 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns = ['id' , 'Unnamed: 32'] , axis = 1 , inplace = True)

In [7]:
# train test split 
X_train , X_test , y_train , y_test = train_test_split(df.iloc[ : , 1 : ] , df.iloc[ : , 0] , test_size = 0.2 , random_state = 42)

In [8]:
scaler = StandardScaler() 

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
y_test

204    B
70     M
131    M
431    B
540    B
      ..
486    B
75     M
249    B
238    B
265    M
Name: diagnosis, Length: 114, dtype: object

In [10]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

In [11]:
label_encoder = LabelEncoder()

y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.transform(y_test)

In [12]:
y_test

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1])

In [13]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,

In [14]:
# converting numpy to tensor 
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [15]:
X_train_tensor.shape

torch.Size([455, 30])

In [33]:
# Define the Neural Network 
class MySimpleNN(): 
    def __init__(self , X): 
        # define random weights
        self.weights = torch.rand(X.shape[1] , 1 , dtype = torch.float64 , requires_grad = True) 
        # define bias 
        self.bias = torch.zeros(1 , dtype = torch.float64 , requires_grad = True)
    
    def forward(self , X): 
        # weighted sum 
        z = torch.matmul(X , self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self , y_pred , y):
        # clamp prediction to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred , min = epsilon , max = 1 - epsilon)

        # calculate sigmoid loss 
        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
        return loss 

    

### Important Parameters

In [34]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [35]:
# creating model 
model = MySimpleNN(X_train_tensor)

In [36]:
model.weights

tensor([[0.1010],
        [0.1795],
        [0.7901],
        [0.2512],
        [0.6777],
        [0.9987],
        [0.6505],
        [0.0472],
        [0.0240],
        [0.4216],
        [0.1073],
        [0.3135],
        [0.3001],
        [0.8910],
        [0.9335],
        [0.7426],
        [0.7226],
        [0.3833],
        [0.5099],
        [0.9100],
        [0.5814],
        [0.3765],
        [0.2250],
        [0.4743],
        [0.3633],
        [0.2675],
        [0.2865],
        [0.9714],
        [0.0965],
        [0.4906]], dtype=torch.float64, requires_grad=True)

In [37]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

### Train the model:
---
- 3 Steps: 
  1. Forward pass
  2. loss calculation
  3. Backward pass 

In [38]:
print("weights requires_grad:", model.weights.requires_grad)
print("bias requires_grad:", model.bias.requires_grad)
for epoch in range(epochs): 
    # forward pass 
    y_pred = model.forward(X_train_tensor)

    # calculate loss 
    loss = model.loss_function(y_pred , y_train_tensor)

    # do the backward pass(find derivatives)
    loss.backward()

    # update weights and bias with no gradient tracking
    with torch.no_grad(): 
      model.weights -= learning_rate * model.weights.grad
      model.bias -= learning_rate * model.bias.grad
    # clear the gradient cause it got accumulated 
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f"Epoch {epoch + 1}: Loss = {loss.item():.4f}")

weights requires_grad: True
bias requires_grad: True
Epoch 1: Loss = 3.4571
Epoch 2: Loss = 3.3248
Epoch 3: Loss = 3.1883
Epoch 4: Loss = 3.0458
Epoch 5: Loss = 2.9023
Epoch 6: Loss = 2.7535
Epoch 7: Loss = 2.5997
Epoch 8: Loss = 2.4458
Epoch 9: Loss = 2.2860
Epoch 10: Loss = 2.1262
Epoch 11: Loss = 1.9705
Epoch 12: Loss = 1.8186
Epoch 13: Loss = 1.6714
Epoch 14: Loss = 1.5324
Epoch 15: Loss = 1.4059
Epoch 16: Loss = 1.2894
Epoch 17: Loss = 1.1860
Epoch 18: Loss = 1.0990
Epoch 19: Loss = 1.0278
Epoch 20: Loss = 0.9710
Epoch 21: Loss = 0.9262
Epoch 22: Loss = 0.8911
Epoch 23: Loss = 0.8634
Epoch 24: Loss = 0.8411
Epoch 25: Loss = 0.8228


In [40]:
# model evaluation 
with torch.no_grad(): 
    y_pred = model.forward(X_test_tensor)
y_pred

tensor([[0.3712],
        [0.3059],
        [0.2850],
        [0.8015],
        [0.8414],
        [0.3449],
        [0.3186],
        [0.3855],
        [0.3793],
        [0.1386],
        [0.3282],
        [0.3837],
        [0.2949],
        [0.8793],
        [0.1705],
        [0.9050],
        [0.3386],
        [0.7679],
        [0.6827],
        [0.2693],
        [0.3246],
        [0.4143],
        [0.2592],
        [0.3217],
        [0.3565],
        [0.7540],
        [0.2344],
        [0.7978],
        [0.3860],
        [0.4485],
        [0.3516],
        [0.3493],
        [0.5418],
        [0.2423],
        [0.5293],
        [0.4329],
        [0.3399],
        [0.2273],
        [0.2657],
        [0.3854],
        [0.4389],
        [0.7026],
        [0.3094],
        [0.4100],
        [0.6628],
        [0.4716],
        [0.8662],
        [0.7039],
        [0.2592],
        [0.5911],
        [0.1973],
        [0.3449],
        [0.3508],
        [0.6507],
        [0.8683],
        [0

In [41]:
y_pred = (y_pred > 0.5).float()
y_pred

tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
      

In [42]:
accuracy = (y_pred == y_test_tensor).float().mean()
accuracy

tensor(0.5323)